// product constants
export const LOAD_PRODUCTS_PENDING = "LOAD_PRODUCTS_PENDING";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const LOAD_PRODUCTS_FAILED = "LOAD_PRODUCTS_FAILED";
export const PRODUCT_DETAILS_PENDING = "PRODUCT_DETAILS_PENDING";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAILED = "PRODUCT_DETAILS_FAILED";
export const PRODUCT_SAVE_PENDING = "PRODUCT_SAVE_PENDING";
export const PRODUCT_SAVE_SUCCESS = "PRODUCT_SAVE_SUCCESS";
export const PRODUCT_SAVE_FAILED = "PRODUCT_SAVE_FAILED";

//cart constants
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT_COUNT = "INCREMENT_COUNT";
export const DECREMENT_COUNT = "DECREMENT_COUNT";
export const EMPTY_CART = "EMPTY_CART";
export const LOAD_CART = "LOAD_CART";
export const CHANGE_QUANTITY = "CHANGE_QUANTITY";
export const CART_SAVE_SHIPPING = "CART_SAVE_SHIPPING";
export const CART_SAVE_PAYMENT = "CART_SAVE_PAYMENT";

//user constants
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAILED = "USER_SIGNIN_FAILED";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";

export const SET_DETAILS_PRODUCT = "SET_DETAILS_PRODUCT";
export const OPEN_LOG_MODAL = "OPEN_LOG_MODAL";
export const CLOSE_LOG_MODAL = "CLOSE_LOG_MODAL";
export const OPEN_ADDTOCART_MODAL = "OPEN_ADDTOCART_MODAL";
export const CLOSE_ADDTOCART_MODAL = "CLOSE_ADDTOCART_MODAL";

export const OPEN_MENU = "OPEN_MENU";
